name: shippingservice - Build images and push to AWS ECR

on:
  push:
    branches:
      - main
    # paths:
    #   - "src/shippingservice/**"

permissions:
  contents: read
  id-token: write

jobs:
  build-and-push-shippingservice:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      # - uses: dorny/paths-filter@v3
      #   id: changes
      #   with:
      #     filters: |
      #       src:
      #         - 'src/shippingservice/**'

      # - name: Check for files changed
      #   if: steps.changes.outputs.src == 'true'
      #   run: echo "Files changed"

      - name: Configure AWS credentials
        # if: steps.changes.outputs.src == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GHA_OIDC_ROLE }}
          aws-region: ap-southeast-1

      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        # if: steps.changes.outputs.src == 'true'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./src/shippingservice
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/microservices-demo/shippingservice:latest
            ${{ steps.login-ecr.outputs.registry }}/microservices-demo/shippingservice:${{ github.sha }}
